services:
  gradio-backend:
    image: ${REGISTRY}/gradio-backend:${GRADIO_BACKEND_VERSION}
    build:
      context: gradio-backend
      args:
        VERSION: ${GRADIO_BACKEND_VERSION}
    volumes:
      - ${MODEL_PATH}:/app/model
    environment:
      MODEL: /app/model
      MODEL_TYPE: ${MODEL_TYPE}
      DEVICE: ${DEVICE}
      GRADIO_ROOT_PATH: ${GRADIO_ROOT_PATH}
    ports:
      - "127.0.0.1:7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    runtime: nvidia


  nginx:
    build:
      context: nginx
    depends_on:
      - gradio-backend
    cap_drop:
      - ALL
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=1024
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/secure-container.local.crt:/etc/nginx/ssl/secure-container.local.crt
      - ./nginx/secure-container.local.key:/etc/nginx/ssl/secure-container.local.key
    ports:
      - "127.0.0.1:8443:8443"
    secrets:
      - ssl_password
      - htpasswd

secrets:
  ssl_password:
    file: ./nginx/ssl-password.txt
  htpasswd:
    file: ./nginx/htpasswd
