services:
  gradio-backend:
    image: ${REGISTRY}/gradio-backend:${GRADIO_BACKEND_VERSION}
    build:
      context: gradio-backend
      args:
        VERSION: ${GRADIO_BACKEND_VERSION}
    volumes:
      - ${MODEL_PATH}:/app/model
    environment:
      MODEL: /app/model
      MODEL_TYPE: ${MODEL_TYPE}
      DEVICE: ${DEVICE}
      GRADIO_ROOT_PATH: ${GRADIO_ROOT_PATH}
    ports:
      - "127.0.0.1:7860:7860"

  nginx:
    image: docker.io/library/nginx:1.27
    depends_on:
      - gradio-backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/secure-container.local.crt:/etc/nginx/ssl/secure-container.local.crt
      - ./nginx/secure-container.local.key:/etc/nginx/ssl/secure-container.local.key
      - ./nginx/.htpasswd:/etc/nginx/conf/.htpasswd
    ports:
      - "127.0.0.1:8443:443"
    secrets:
      - ssl_password

secrets:
  ssl_password:
    file: ./nginx/ssl-password.txt
